### ISSUE TITLE
Add lowcoder to "Visual programming"

### ISSUE THREAD

**Issue by sobir-git** [antdimot/awesome-lowcode#20]
https://lowcoder.cloud/

Lowcoder is a low-code platform that allows users to build custom software applications with minimal coding. It provides a visual editor, pre-built components, and options for self-hosting or cloud deployment. Lowcoder is positioned as an alternative to other low-code tools like Retool and Appsmith, enabling faster application development for businesses and individuals.

**Comment by antdimot** [comment]
Added. Thank you for your suggestion.
